# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    START_ORDER_HOUR: "09"
    START_ORDER_MIN: "15"
    END_ORDER_HOUR: "23"
    END_ORDER_MIN: "30"

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.reservation:
        class: AppBundle\Service\ReservationService
        arguments: ['@service_container']
